### ISSUE TITLE
Morpho Blue adapter Questions

### ISSUE THREAD

**Issue by tomrpl** [consensys-vertical-apps/mmi-defi-adapters#143]
Hello @bergarces 

While implementing the adapter for Morpho Blue, the new Morpho protocol released few days ago, I realized that I got some issue with the DeFiProvider.

I'll explain myself:
A bit like Uniswap with its different pools, Morpho Blue has several Markets and no 'protocolTokens' but the design is that several markets are created as follows:

e.g. 
1. wstETH/WETH (ChainlinkOracle: WETH (wstETH), AdaptiveCurveIRM,94.5%)
with the id (could be seen as a unique identifier for a given market):
0xc54d7acf14de29e0e5527cabd7a576506870346a78a11a6762e2cca66322ec41

2. wstETH/USDC (ChainlinkOracle: USDC (wstETH), AdaptiveCurveIRM, 94.5%)
3. wstETH/USDC (ChainlinkOracle: USDC (wstETH), AdaptiveCurveIRM, 92%)
...

As per the doc there:
https://docs.morpho.org/addresses#morpho-blue-whitelisted-markets

My concern is that then there are multiple markets where WETH or USDC (or any "loan token") could be used into, and thus apy's and apr's are different from one market to another one.

Thus my trouble is that by having the getApr, getApy and getPrice functions using getProtocolTokens, 

- https://github.com/consensys-vertical-apps/mmi-defi-adapters/blob/main/src/defiProvider.ts#L211,
- https://github.com/consensys-vertical-apps/mmi-defi-adapters/blob/main/src/defiProvider.ts#L393,
- https://github.com/consensys-vertical-apps/mmi-defi-adapters/blob/main/src/defiProvider.ts#L425

It is blocking me to adapt the getProtocolTokens to return the ID of the different params. the market ID as argument inside.  

I would rather not create a specific defiProvider for Morpho Blue only.

Do you have any work-around for this?
If easier to discuss about it, feel free to DM me here on tg:

@tom_morpho
Cheers

**Comment by tomrpl** [comment]
Little bump here @bergarces in case you have a quickwin in mind

**Comment by jpsains** [comment]
Hey Tom,

It was good working with you to resolve this. 

Solution: We introduced a new param 'tokenId' so that non standard erc20 pools could be queried by an id called tokenId
